### ISSUE TITLE
Problem with neutrino tables

### ISSUE THREAD

**Issue by carmeloevoli** [aafragpy/aafragpy#1]
Hi! I'm wondering if there is a bug with the neutrino tables.

As far as I understand, tables with name ending with *L* are for lower projectile energies, while the same tables without *L* are for higher energies.  That it works fine for all tables but `nu_He_p_04`. 

Indeed, while `nu_He_p_04L` covers primary energies from 5 to 10 GeV (as all the other low-energy tables), `nu_He_p_04` table starts with primary energy 15.848 GeV (differently than all the other high-energy tables which start with 10 GeV).

**Comment by skoldobskiy** [comment]
Hi Carmelo!
Thanks for noticing it, it was the bug; I have fixed it.
Now you can download an updated version of `nu_He_p_04`.

**Comment by carmeloevoli** [comment]
Thanks for the fast reply! 
Please notice that also `nu_He_He_04` has the same problem, sorry not mentioning before :(

**Comment by skoldobskiy** [comment]
Thanks again, fixed it!
